apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: codeparce-devops
spec:
  selector:
    app: gitlab
  ports:
    - name: http       # ðŸ”¹ nombre obligatorio y Ãºnico
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 2222
      targetPort: 2222
  type: ClusterIP