version: "3.9"

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    restart: unless-stopped
    ports:
      - "2049:2049"    # puerto NFS
      - "111:111"      # portmap
    privileged: true
    environment:
      SHARED_DIRECTORY: /nfsshare
    volumes:
      - ./nfs-share:/nfsshare   # carpeta local que se comparte
    networks:
      - k3d-dev
networks:
  k3d-dev:
    external: true