apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server # Cambia esto por la IP o hostname de tu servidor NFS
    path: /nfsshare
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs"

# docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nfs-server
